### ISSUE TITLE
请教下，使用echarts打包后的vendor文件太大的问题是如何解决的

### ISSUE THREAD

**Issue by zhongxiangbin** [gengchen528/alumin-connect#1]

**Comment by gengchen528** [comment]
这个问题只有在npm run start的时候出现太大，当npm run build的时候就可以了

**Comment by zhongxiangbin** [comment]
可是即使是npm run build之后vendor文件依旧有879KB，微信开发者工具里单个js文件超过500kB就有警告了

**Comment by gengchen528** [comment]
> 可是即使是npm run build之后vendor文件依旧有879KB，微信开发者工具里单个js文件超过500kB就有警告了

你可以再echarts官网在线定制你需要的图表  或者 使用小程序的分包机制来处理一下

**Comment by zhongxiangbin** [comment]
那你这里是怎么处理小程序代码打包上传的呢，你这个小程序打包后vendor就有879KB，我之前有项目是只用到了雷达图，没有按需加载的办法，所以手动删掉了echarts包里面其他的图表只留下`require("./lib/chart/radar");`，才将vendor缩减到了300+KB，对于mpvue如何分包这个我也不太熟悉。。。

**Comment by zhongxiangbin** [comment]
好的，谢谢了！
