### ISSUE TITLE
大神，问下wxparser 的用法

### ISSUE THREAD

**Issue by shiqikai** [gengchen528/alumin-connect#3]
` <wxparser :rich-text="richText" />  `
这样显示不出来。
` <wxparser v-html="richText" />`

这样倒是可以。

你的用法就是第一种呀 但是我这边怎么就是不能显示呢

**Comment by gengchen528** [comment]
> `<wxparser :rich-text="richText" /> `
> 这样显示不出来。
> ` <wxparser v-html="richText" />`
> 
> 这样倒是可以。
> 
> 你的用法就是第一种呀 但是我这边怎么就是不能显示呢

这里我使用的是小程序的插件功能，并不是npm安装的

**Comment by shiqikai** [comment]
> > `<wxparser :rich-text="richText" /> `
> > 这样显示不出来。
> > ` <wxparser v-html="richText" />`
> > 这样倒是可以。
> > 你的用法就是第一种呀 但是我这边怎么就是不能显示呢
> 
> 这里我使用的是小程序的插件功能，并不是npm安装的

我也是小程序里配置了这个插件  用法一模一样 就是显示不出来呀

**Comment by shiqikai** [comment]
![image](https://user-images.githubusercontent.com/10249745/52690782-c69a1800-2f99-11e9-9430-8fdb2e3e2c59.png)
尴尬的是我在官方下提问 说不支持mpvue  但是你的已经显示成功了啊

**Comment by gengchen528** [comment]
我使用的话也没有什么特殊，就是main.js 中和页面的main.js中进行了配置，直接在页面上使用就可以了，这个插件我估计他们也没有认真测试过mpvue下的兼容性，所以说不支持吧。如果使用v-html也可以的话，那你就不用纠结这个问题了

**Comment by shiqikai** [comment]
小程序配置那边  要配置图片的合法域名或者request域名什么的不？

**Comment by gengchen528** [comment]
图片是不需要设置合法域名，你是图片无法显示还是文字图片都不显示呢

**Comment by shiqikai** [comment]
https://github.com/F-loat/mpvue-wxParse 我用这个是图片不能显示。
但是跟你这个一样的配置一样的写法是 一点都不显示（但是控制台没报错）
很蛋疼

**Comment by gengchen528** [comment]
我重新建了一个mpvue代码片段，使用了小程序富文本解析插件，也是可以的，你可以加我V信：CG12104410
